version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: GesturaApp_MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - gesturaapp_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: GesturaApp_phpMyAdmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - gesturaapp_network

volumes:
  mysql_data:

networks:
  gesturaapp_network:
    driver: bridge
